"""empty message

Revision ID: a365476ba26a
Revises: ca721919f400
Create Date: 2024-09-12 13:02:09.518797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a365476ba26a'
down_revision = 'ca721919f400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', mysql.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
